spring.http.clients.connect-timeout=2s
spring.http.clients.read-timeout=5s

spring.http.serviceclient.account-group.base-url=http://localhost:8081
spring.http.serviceclient.account.base-url=http://localhost:8083
spring.http.serviceclient.owners.base-url=http://localhost:8084
