spring.http.clients.connect-timeout=2s
spring.http.clients.read-timeout=5s
spring.http.clients.reactive.connector=reactor

spring.http.serviceclient.account-group.base-url=http://localhost:8081
spring.http.serviceclient.account.base-url=http://localhost:8083
spring.http.serviceclient.owners.base-url=http://localhost:8084

management.endpoints.web.exposure.include=health,info,metrics
management.endpoints.access.default=none
management.endpoint.health.access=read-only
management.endpoint.info.access=read-only
management.endpoint.metrics.access=read-only
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=webflux
