spring:
  http:
    clients:
      connect-timeout: 2s
      read-timeout: 5s
      reactive:
        connector: reactor
    serviceclient:
      account-group:
        base-url: http://localhost:8081
        read-timeout: 2s
      account:
        base-url: http://localhost:8083
        read-timeout: 3s
      owners:
        base-url: http://localhost:8084
        read-timeout: 3s
  webflux:
    problemdetails:
      enabled: true
  reactor:
    context-propagation: auto

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
    access:
      default: none
  endpoint:
    health:
      access: read-only
      probes:
        enabled: true
    info:
      access: read-only
    metrics:
      access: read-only
  metrics:
    tags:
      application: aggregation-gateway
